14:46:50

school solution#User solution#result#Test name


while testing \BaraksTests\if\01.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\BaraksTests\if\02.sjava		

while testing \BaraksTests\if\03.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \BaraksTests\if\04.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\BaraksTests\if\05.sjava		##################################
0		1		failed		\BaraksTests\if\06.sjava		##################################
0		1		failed		\BaraksTests\if\07.sjava		##################################
0		1		failed		\BaraksTests\if\08.sjava		##################################
0		1		failed		\BaraksTests\if\09.sjava		##################################
0		1		failed		\BaraksTests\if\10.sjava		##################################
0		1		failed		\BaraksTests\if\11.sjava		##################################
1		1		passed		\BaraksTests\if\12.sjava		
1		1		passed		\BaraksTests\if\13.sjava		
0		1		failed		\BaraksTests\if\14.sjava		##################################
1		1		passed		\BaraksTests\if\15.sjava		
1		1		passed		\BaraksTests\if\16.sjava		
1		1		passed		\BaraksTests\if\17.sjava		
1		1		passed		\BaraksTests\if\18.sjava		
1		1		passed		\BaraksTests\if\22.sjava		
1		1		passed		\BaraksTests\if\23.sjava		
1		1		passed		\BaraksTests\if\24.sjava		
1		1		passed		\BaraksTests\if\25.sjava		
1		1		passed		\BaraksTests\if\26.sjava		
1		1		passed		\BaraksTests\if\27.sjava		
1		1		passed		\BaraksTests\if\28.sjava		

while testing \BaraksTests\if\29.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \BaraksTests\if\30.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\BaraksTests\if\31.sjava		
0		1		failed		\BaraksTests\methods\01.sjava		##################################
1		1		passed		\BaraksTests\methods\02.sjava		
0		1		failed		\BaraksTests\methods\03.sjava		##################################
0		1		failed		\BaraksTests\methods\04.sjava		##################################
0		1		failed		\BaraksTests\methods\06.sjava		##################################
0		1		failed		\BaraksTests\methods\07.sjava		##################################
1		1		passed		\BaraksTests\methods\08.sjava		
1		1		passed		\BaraksTests\methods\09.sjava		
1		1		passed		\BaraksTests\methods\10.sjava		
1		1		passed		\BaraksTests\methods\11.sjava		
1		1		passed		\BaraksTests\methods\12.sjava		
1		1		passed		\BaraksTests\methods\13.sjava		
0		1		failed		\BaraksTests\methods\14.sjava		##################################
1		1		passed		\BaraksTests\methods\16.sjava		
1		1		passed		\BaraksTests\methods\17.sjava		
0		1		failed		\BaraksTests\methods\18.sjava		##################################
1		1		passed		\BaraksTests\methods\19.sjava		
1		1		passed		\BaraksTests\methods\20.sjava		
1		1		passed		\BaraksTests\methods\21.sjava		
1		1		passed		\BaraksTests\methods\22.sjava		
1		1		passed		\BaraksTests\methods\23.sjava		
1		1		passed		\BaraksTests\methods\24.sjava		
0		1		failed		\BaraksTests\methods\25.sjava		##################################
1		1		passed		\BaraksTests\methods\26.sjava		
0		1		failed		\BaraksTests\methods\27.sjava		##################################
1		1		passed		\BaraksTests\methods\28.sjava		
0		1		failed		\BaraksTests\methods\29.sjava		##################################
1		1		passed		\BaraksTests\methods\31.sjava		
0		1		failed		\BaraksTests\methods\32.sjava		##################################
0		1		failed		\BaraksTests\methods\33.sjava		##################################
0		1		failed		\BaraksTests\methods\34.sjava		##################################
1		1		passed		\BaraksTests\methods\35.sjava		
1		1		passed		\BaraksTests\methods\37.sjava		
0		1		failed		\BaraksTests\return\01.sjava		##################################
0		1		failed		\BaraksTests\return\02.sjava		##################################
1		1		passed		\BaraksTests\return\03.sjava		
1		1		passed		\BaraksTests\return\04.sjava		
1		1		passed		\BaraksTests\return\05.sjava		
1		1		passed		\BaraksTests\return\06.sjava		
0		1		failed		\BaraksTests\return\07.sjava		##################################
0		1		failed		\BaraksTests\return\08.sjava		##################################
0		1		failed		\BaraksTests\return\09.sjava		##################################
1		1		passed		\BaraksTests\return\10.sjava		
0		1		failed		\BaraksTests\return\11.sjava		##################################
1		1		passed		\BaraksTests\return\12.sjava		

while testing \BaraksTests\return\13.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\BaraksTests\return\14.sjava		##################################

while testing \BaraksTests\structure\01.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.ArrayIndexOutOfBoundsException: 2
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:37)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\BaraksTests\structure\02.sjava		
1		1		passed		\BaraksTests\structure\03.sjava		
0		1		failed		\BaraksTests\structure\04.sjava		##################################
0		1		failed		\BaraksTests\structure\05.sjava		##################################
0		1		failed		\BaraksTests\structure\06.sjava		##################################
0		1		failed		\BaraksTests\structure\07.sjava		##################################
0		1		failed		\BaraksTests\structure\08.sjava		##################################
1		1		passed		\BaraksTests\structure\09.sjava		
1		1		passed		\BaraksTests\structure\10.sjava		
1		1		passed		\BaraksTests\structure\11.sjava		
1		1		passed		\BaraksTests\structure\12.sjava		
1		1		passed		\BaraksTests\structure\13.sjava		
1		1		passed		\BaraksTests\structure\14.sjava		
1		1		passed		\BaraksTests\structure\15.sjava		
1		1		passed		\BaraksTests\structure\16.sjava		
1		1		passed		\BaraksTests\structure\17.sjava		
1		1		passed		\BaraksTests\structure\18.sjava		
1		1		passed		\BaraksTests\structure\19.sjava		
1		1		passed		\BaraksTests\structure\20.sjava		
1		1		passed		\BaraksTests\structure\21.sjava		
1		1		passed		\BaraksTests\structure\22.sjava		
1		1		passed		\BaraksTests\structure\23.sjava		
1		1		passed		\BaraksTests\structure\24.sjava		
1		1		passed		\BaraksTests\structure\25.sjava		

while testing \BaraksTests\variables\01.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.ArrayIndexOutOfBoundsException: 5
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:55)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\BaraksTests\variables\02.sjava		##################################
1		1		passed		\BaraksTests\variables\03.sjava		
1		1		passed		\BaraksTests\variables\04.sjava		
1		1		passed		\BaraksTests\variables\05.sjava		
1		1		passed		\BaraksTests\variables\06.sjava		
1		1		passed		\BaraksTests\variables\07.sjava		
1		1		passed		\BaraksTests\variables\08.sjava		
1		1		passed		\BaraksTests\variables\09.sjava		
1		1		passed		\BaraksTests\variables\10.sjava		
1		1		passed		\BaraksTests\variables\11.sjava		
1		1		passed		\BaraksTests\variables\12.sjava		
1		1		passed		\BaraksTests\variables\13.sjava		
1		1		passed		\BaraksTests\variables\14.sjava		
1		1		passed		\BaraksTests\variables\15.sjava		
0		1		failed		\BaraksTests\variables\16.sjava		##################################
1		1		passed		\BaraksTests\variables\17.sjava		
1		1		passed		\BaraksTests\variables\18.sjava		
0		1		failed		\BaraksTests\variables\19.sjava		##################################
0		1		failed		\BaraksTests\variables\20.sjava		##################################
0		1		failed		\BaraksTests\variables\21.sjava		##################################
0		1		failed		\BaraksTests\variables\22.sjava		##################################
0		1		failed		\BaraksTests\variables\23.sjava		##################################
1		1		passed		\BaraksTests\variables\24.sjava		
1		1		passed		\BaraksTests\variables\25.sjava		
1		1		passed		\BaraksTests\variables\26.sjava		
0		1		failed		\BaraksTests\variables\27.sjava		##################################
1		1		passed		\BaraksTests\variables\28.sjava		
1		1		passed		\BaraksTests\variables\29.sjava		
1		1		passed		\BaraksTests\variables\30.sjava		
1		1		passed		\BaraksTests\variables\31.sjava		
1		1		passed		\BaraksTests\variables\32.sjava		
1		1		passed		\BaraksTests\variables\33.sjava		
1		1		passed		\BaraksTests\variables\34.sjava		
0		1		failed		\BaraksTests\variables\35.sjava		##################################
1		1		passed		\BaraksTests\variables\36.sjava		
1		1		passed		\BaraksTests\variables\37.sjava		
1		1		passed		\BaraksTests\variables\38.sjava		
1		1		passed		\BaraksTests\variables\39.sjava		
1		1		passed		\BaraksTests\variables\40.sjava		
0		1		failed		\BaraksTests\variables\41.sjava		##################################
0		1		failed		\BaraksTests\variables\42.sjava		##################################
0		1		failed		\BaraksTests\variables\43.sjava		##################################
1		1		passed		\BaraksTests\variables\44.sjava		
0		1		failed		\BaraksTests\variables\45.sjava		##################################
1		1		passed		\BaraksTests\variables\46.sjava		
1		1		passed		\BaraksTests\variables\47.sjava		
1		1		passed		\BaraksTests\variables\48.sjava		
0		1		failed		\BaraksTests\variables\49.sjava		##################################
0		1		failed		\BaraksTests\variables\50.sjava		##################################
1		1		passed		\BaraksTests\variables\51.sjava		
1		1		passed		\BaraksTests\variables\52.sjava		
1		1		passed		\BaraksTests\variables\53.sjava		
0		1		failed		\BaraksTests\variables\54.sjava		##################################
0		1		failed		\BaraksTests\variables\55.sjava		##################################
0		1		failed		\BaraksTests\variables\56.sjava		##################################
1		1		passed		\BaraksTests\variables\57.sjava		
1		1		passed		\BaraksTests\variables\58.sjava		
1		1		passed		\BaraksTests\variables\59.sjava		
1		1		passed		\BaraksTests\variables\60.sjava		
1		1		passed		\BaraksTests\variables\61.sjava		
1		1		passed		\BaraksTests\variables\62.sjava		
1		1		passed		\BaraksTests\variables\63.sjava		
1		1		passed		\BaraksTests\variables\64.sjava		
1		1		passed		\BaraksTests\variables\65.sjava		
0		1		failed		\BaraksTests\variables\66.sjava		##################################
1		1		passed		\BaraksTests\variables\67.sjava		
1		1		passed		\BaraksTests\variables\68.sjava		
0		1		failed		\BaraksTests\variables\69.sjava		##################################
0		1		failed		\BaraksTests\variables\70.sjava		##################################
1		1		passed		\BaraksTests\variables\71.sjava		
1		1		passed		\BaraksTests\variables\72.sjava		

while testing \BaraksTests\variables\73.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \BaraksTests\variables\74.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\BaraksTests\variables\75.sjava		##################################
0		1		failed		\BaraksTests\variables\76.sjava		##################################

while testing \BaraksTests\variables\77.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \BaraksTests\variables\78.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \BaraksTests\variables\79.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\BaraksTests\variables\80.sjava		##################################
1		1		passed		\BaraksTests\variables\81.sjava		
0		1		failed		\BaraksTests\variables\82.sjava		##################################
0		1		failed		\BaraksTests\variables\83.sjava		##################################
0		1		failed		\BaraksTests\variables\84.sjava		##################################
1		1		passed		\BaraksTests\variables\85.sjava		
0		1		failed		\BaraksTests\variables\86.sjava		##################################
1		1		passed		\BaraksTests\variables\87.sjava		
1		1		passed		\BaraksTests\variables\88.sjava		
1		1		passed		\BaraksTests\variables\89.sjava		
1		1		passed		\BaraksTests\variables\90.sjava		
1		1		passed		\BaraksTests\variables\91.sjava		
1		1		passed		\BaraksTests\variables\92.sjava		
1		1		passed		\BaraksTests\variables\93.sjava		
1		1		passed		\BaraksTests\variables\94.sjava		
1		1		passed		\BaraksTests\variables\95.sjava		

while testing \BaraksTests\while\01.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\BaraksTests\while\02.sjava		

while testing \BaraksTests\while\03.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \BaraksTests\while\04.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\BaraksTests\while\05.sjava		##################################
0		1		failed		\BaraksTests\while\06.sjava		##################################
0		1		failed		\BaraksTests\while\07.sjava		##################################
0		1		failed		\BaraksTests\while\08.sjava		##################################
0		1		failed		\BaraksTests\while\09.sjava		##################################
0		1		failed		\BaraksTests\while\10.sjava		##################################
0		1		failed		\BaraksTests\while\11.sjava		##################################
1		1		passed		\BaraksTests\while\12.sjava		
1		1		passed		\BaraksTests\while\13.sjava		
0		1		failed		\BaraksTests\while\14.sjava		##################################
1		1		passed		\BaraksTests\while\15.sjava		
1		1		passed		\BaraksTests\while\16.sjava		
1		1		passed		\BaraksTests\while\17.sjava		
1		1		passed		\BaraksTests\while\18.sjava		
1		1		passed		\BaraksTests\while\22.sjava		
1		1		passed		\BaraksTests\while\23.sjava		
1		1		passed		\BaraksTests\while\24.sjava		
1		1		passed		\BaraksTests\while\25.sjava		
1		1		passed		\BaraksTests\while\26.sjava		
1		1		passed		\BaraksTests\while\27.sjava		
1		1		passed		\BaraksTests\while\28.sjava		
0		1		failed		\SchoolTests\test001.sjava		##################################
0		1		failed		\SchoolTests\test002.sjava		##################################
0		1		failed		\SchoolTests\test003.sjava		##################################
0		1		failed		\SchoolTests\test004.sjava		##################################
1		1		passed		\SchoolTests\test005.sjava		
1		1		passed		\SchoolTests\test006.sjava		
1		1		passed		\SchoolTests\test007.sjava		
1		1		passed		\SchoolTests\test008.sjava		
0		1		failed		\SchoolTests\test009.sjava		##################################
0		1		failed		\SchoolTests\test011.sjava		##################################
0		1		failed		\SchoolTests\test012.sjava		##################################
0		1		failed		\SchoolTests\test013.sjava		##################################
0		1		failed		\SchoolTests\test014.sjava		##################################
0		1		failed		\SchoolTests\test015.sjava		##################################
1		1		passed		\SchoolTests\test016.sjava		
1		1		passed		\SchoolTests\test017.sjava		
1		1		passed		\SchoolTests\test018.sjava		
0		1		failed		\SchoolTests\test019.sjava		##################################
0		1		failed		\SchoolTests\test021.sjava		##################################
0		1		failed		\SchoolTests\test022.sjava		##################################
1		1		passed		\SchoolTests\test023.sjava		
1		1		passed		\SchoolTests\test024.sjava		
1		1		passed		\SchoolTests\test025.sjava		
1		1		passed		\SchoolTests\test026.sjava		
0		1		failed		\SchoolTests\test027.sjava		##################################
0		1		failed		\SchoolTests\test028.sjava		##################################
1		1		passed		\SchoolTests\test029.sjava		
0		1		failed		\SchoolTests\test030.sjava		##################################
0		1		failed		\SchoolTests\test031.sjava		##################################
0		1		failed		\SchoolTests\test032.sjava		##################################
0		1		failed		\SchoolTests\test033.sjava		##################################
0		1		failed		\SchoolTests\test034.sjava		##################################
0		1		failed		\SchoolTests\test035.sjava		##################################
1		1		passed		\SchoolTests\test036.sjava		
1		1		passed		\SchoolTests\test037.sjava		
1		1		passed		\SchoolTests\test038.sjava		
0		1		failed		\SchoolTests\test039.sjava		##################################
0		1		failed		\SchoolTests\test041.sjava		##################################
0		1		failed		\SchoolTests\test042.sjava		##################################
0		1		failed		\SchoolTests\test043.sjava		##################################
1		1		passed		\SchoolTests\test044.sjava		
1		1		passed		\SchoolTests\test045.sjava		
1		1		passed		\SchoolTests\test046.sjava		
1		1		passed		\SchoolTests\test047.sjava		
1		1		passed		\SchoolTests\test048.sjava		
1		1		passed		\SchoolTests\test049.sjava		
0		1		failed		\SchoolTests\test050.sjava		##################################
0		1		failed		\SchoolTests\test051.sjava		##################################
1		1		passed		\SchoolTests\test052.sjava		
1		1		passed		\SchoolTests\test053.sjava		
1		1		passed		\SchoolTests\test054.sjava		
1		1		passed		\SchoolTests\test055.sjava		
0		1		failed		\SchoolTests\test056.sjava		##################################
1		1		passed		\SchoolTests\test057.sjava		
0		1		failed		\SchoolTests\test058.sjava		##################################
0		1		failed		\SchoolTests\test059.sjava		##################################
1		1		passed		\SchoolTests\test061.sjava		
1		1		passed		\SchoolTests\test062.sjava		
1		1		passed		\SchoolTests\test063.sjava		
1		1		passed		\SchoolTests\test064.sjava		
1		1		passed		\SchoolTests\test065.sjava		
1		1		passed		\SchoolTests\test066.sjava		
1		1		passed		\SchoolTests\test067.sjava		
1		1		passed		\SchoolTests\test101.sjava		
1		1		passed		\SchoolTests\test102.sjava		
1		1		passed		\SchoolTests\test103.sjava		
1		1		passed		\SchoolTests\test104.sjava		
1		1		passed		\SchoolTests\test105.sjava		
0		1		failed		\SchoolTests\test106.sjava		##################################
0		1		failed		\SchoolTests\test107.sjava		##################################
0		1		failed		\SchoolTests\test108.sjava		##################################
0		1		failed		\SchoolTests\test109.sjava		##################################
0		1		failed		\SchoolTests\test110.sjava		##################################
0		1		failed		\SchoolTests\test111.sjava		##################################
0		1		failed		\SchoolTests\test112.sjava		##################################
0		1		failed		\SchoolTests\test113.sjava		##################################
1		1		passed		\SchoolTests\test114.sjava		
1		1		passed		\SchoolTests\test115.sjava		
1		1		passed		\SchoolTests\test116.sjava		
1		1		passed		\SchoolTests\test117.sjava		
0		1		failed		\SchoolTests\test201.sjava		##################################
0		1		failed		\SchoolTests\test202.sjava		##################################
0		1		failed		\SchoolTests\test203.sjava		##################################
0		1		failed		\SchoolTests\test204.sjava		##################################
1		1		passed		\SchoolTests\test205.sjava		
1		1		passed		\SchoolTests\test206.sjava		
1		1		passed		\SchoolTests\test207.sjava		
1		1		passed		\SchoolTests\test208.sjava		
0		1		failed		\SchoolTests\test209.sjava		##################################
0		1		failed		\SchoolTests\test211.sjava		##################################
0		1		failed		\SchoolTests\test212.sjava		##################################
0		1		failed		\SchoolTests\test213.sjava		##################################
0		1		failed		\SchoolTests\test214.sjava		##################################
0		1		failed		\SchoolTests\test215.sjava		##################################
1		1		passed		\SchoolTests\test216.sjava		
1		1		passed		\SchoolTests\test217.sjava		
1		1		passed		\SchoolTests\test218.sjava		
0		1		failed		\SchoolTests\test219.sjava		##################################
0		1		failed		\SchoolTests\test221.sjava		##################################
0		1		failed		\SchoolTests\test222.sjava		##################################
1		1		passed		\SchoolTests\test223.sjava		
1		1		passed		\SchoolTests\test224.sjava		
1		1		passed		\SchoolTests\test225.sjava		
1		1		passed		\SchoolTests\test226.sjava		
0		1		failed		\SchoolTests\test227.sjava		##################################
0		1		failed		\SchoolTests\test231.sjava		##################################
0		1		failed		\SchoolTests\test232.sjava		##################################
0		1		failed		\SchoolTests\test233.sjava		##################################
0		1		failed		\SchoolTests\test234.sjava		##################################
0		1		failed		\SchoolTests\test235.sjava		##################################
1		1		passed		\SchoolTests\test236.sjava		
1		1		passed		\SchoolTests\test237.sjava		
1		1		passed		\SchoolTests\test238.sjava		
0		1		failed		\SchoolTests\test239.sjava		##################################
0		1		failed		\SchoolTests\test241.sjava		##################################
0		1		failed		\SchoolTests\test242.sjava		##################################
0		1		failed		\SchoolTests\test243.sjava		##################################
1		1		passed		\SchoolTests\test244.sjava		
1		1		passed		\SchoolTests\test245.sjava		
1		1		passed		\SchoolTests\test246.sjava		
1		1		passed		\SchoolTests\test247.sjava		
1		1		passed		\SchoolTests\test248.sjava		
1		1		passed		\SchoolTests\test249.sjava		
1		1		passed		\SchoolTests\test250.sjava		
0		1		failed		\SchoolTests\test251.sjava		##################################
1		1		passed		\SchoolTests\test252.sjava		
0		1		failed		\SchoolTests\test253.sjava		##################################
1		1		passed		\SchoolTests\test254.sjava		
0		1		failed		\SchoolTests\test255.sjava		##################################
1		1		passed		\SchoolTests\test257.sjava		
1		1		passed		\SchoolTests\test261.sjava		
1		1		passed		\SchoolTests\test262.sjava		
1		1		passed		\SchoolTests\test263.sjava		
1		1		passed		\SchoolTests\test264.sjava		
1		1		passed		\SchoolTests\test265.sjava		
0		1		failed		\SchoolTests\test266.sjava		##################################
0		1		failed		\SchoolTests\test267.sjava		##################################
1		1		passed		\SchoolTests\test268.sjava		
1		1		passed		\SchoolTests\test269.sjava		
1		1		passed		\SchoolTests\test270.sjava		
0		1		failed		\SchoolTests\test271.sjava		##################################
1		1		passed		\SchoolTests\test272.sjava		
1		1		passed		\SchoolTests\test273.sjava		
1		1		passed		\SchoolTests\test274.sjava		

while testing \SchoolTests\test291.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test301.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test302.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test303.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test305.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test306.sjava		
1		1		passed		\SchoolTests\test307.sjava		
1		1		passed		\SchoolTests\test308.sjava		
1		1		passed		\SchoolTests\test309.sjava		
1		1		passed		\SchoolTests\test310.sjava		
0		1		failed		\SchoolTests\test311.sjava		##################################

while testing \SchoolTests\test312.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test313.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test314.sjava		

while testing \SchoolTests\test315.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test316.sjava		

while testing \SchoolTests\test321.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test322.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test323.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test324.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\SchoolTests\test325.sjava		##################################
0		1		failed		\SchoolTests\test326.sjava		##################################
0		1		failed		\SchoolTests\test327.sjava		##################################
1		1		passed		\SchoolTests\test328.sjava		
1		1		passed		\SchoolTests\test401.sjava		
1		1		passed		\SchoolTests\test402.sjava		
1		1		passed		\SchoolTests\test403.sjava		
0		1		failed		\SchoolTests\test404.sjava		##################################
0		1		failed		\SchoolTests\test405.sjava		##################################
1		1		passed		\SchoolTests\test406.sjava		
1		1		passed		\SchoolTests\test407.sjava		
1		1		passed		\SchoolTests\test408.sjava		
1		1		passed		\SchoolTests\test409.sjava		

while testing \SchoolTests\test410.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

0		1		failed		\SchoolTests\test411.sjava		##################################
0		1		failed		\SchoolTests\test412.sjava		##################################
1		1		passed		\SchoolTests\test413.sjava		
0		1		failed		\SchoolTests\test414.sjava		##################################
1		1		passed		\SchoolTests\test415.sjava		

while testing \SchoolTests\test416.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.ArrayIndexOutOfBoundsException: 1
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test417.sjava		
0		1		failed		\SchoolTests\test418.sjava		##################################
1		1		passed		\SchoolTests\test420.sjava		
1		1		passed		\SchoolTests\test421.sjava		
1		1		passed		\SchoolTests\test422.sjava		
1		1		passed		\SchoolTests\test423.sjava		
0		1		failed		\SchoolTests\test425.sjava		##################################
0		1		failed		\SchoolTests\test427.sjava		##################################
0		1		failed		\SchoolTests\test428.sjava		##################################
1		1		passed		\SchoolTests\test429.sjava		
1		1		passed		\SchoolTests\test430.sjava		
1		1		passed		\SchoolTests\test431.sjava		
0		1		failed		\SchoolTests\test432.sjava		##################################

while testing \SchoolTests\test433.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test434.sjava		
1		1		passed		\SchoolTests\test435.sjava		
1		1		passed		\SchoolTests\test436.sjava		
0		1		failed		\SchoolTests\test437.sjava		##################################

while testing \SchoolTests\test438.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test439.sjava		
1		1		passed		\SchoolTests\test440.sjava		
1		1		passed		\SchoolTests\test441.sjava		
1		1		passed		\SchoolTests\test442.sjava		

while testing \SchoolTests\test451.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test452.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test453.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.NullPointerException
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:52)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test454.sjava		
1		1		passed		\SchoolTests\test455.sjava		
1		1		passed		\SchoolTests\test456.sjava		
1		1		passed		\SchoolTests\test457.sjava		
1		1		passed		\SchoolTests\test458.sjava		
1		1		passed		\SchoolTests\test459.sjava		
1		1		passed		\SchoolTests\test460.sjava		

while testing \SchoolTests\test461.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.ArrayIndexOutOfBoundsException: 1
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test462.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.ArrayIndexOutOfBoundsException: 1
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


while testing \SchoolTests\test463.sjava, Your program printed something that is not '1' or '0' or '2'.
The prints were:

java.lang.ArrayIndexOutOfBoundsException: 1
	at oop.ex6.main.Blocks.SubBlock.run(SubBlock.java:30)
	at oop.ex6.main.Blocks.MasterBlock.run(MasterBlock.java:190)
	at oop.ex6.main.Sjavac.main(Sjavac.java:50)
	at Tester_ex6_oop.runTestWithOnUser(Tester_ex6_oop.java:302)
	at Tester_ex6_oop.doOneTest(Tester_ex6_oop.java:207)
	at Tester_ex6_oop.runAllTests(Tester_ex6_oop.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

1		1		passed		\SchoolTests\test464.sjava		
0		1		failed		\SchoolTests\test465.sjava		##################################
0		1		failed		\SchoolTests\test466.sjava		##################################
1		1		passed		\SchoolTests\test467.sjava		
1		1		passed		\SchoolTests\test468.sjava		
0		1		failed		\SchoolTests\test469.sjava		##################################
1		1		passed		\SchoolTests\test470.sjava		
1		1		passed		\SchoolTests\test471.sjava		
0		1		failed		\SchoolTests\test472.sjava		##################################
0		1		failed		\SchoolTests\test473.sjava		##################################
1		1		passed		\SchoolTests\test474.sjava		
1		1		passed		\SchoolTests\test475.sjava		
1		1		passed		\SchoolTests\test476.sjava		
1		1		passed		\SchoolTests\test477.sjava		
0		1		failed		\SchoolTests\test501.sjava		##################################
1		1		passed		\SchoolTests\test502.sjava		
1		1		passed		\SchoolTests\test503.sjava		
1		1		passed		\SchoolTests\test504.sjava		
0		1		failed		\SchoolTests\test505.sjava		##################################

passed 263 out of 459 tests.

